### ISSUE TITLE
How to close IClient explicitly?

### ISSUE THREAD

**Issue by ridvan70** [openshift/openshift-restclient-java#390] opened 2019-06-23 16:14 UTC
Hi,

can an instance of IClient be closed explicitly?

Regards
Ridvan

**Comment by adietish** [comment] 2019-06-24 12:17
Hi @ridvan70,

Given that it's a REST client, connections are short lived and limited to a single query and response. There's actually no need to explicitly disconnect the client. Am I missing something?

Cheers
André

**Comment by ridvan70** [comment] 2019-06-24 12:44
Hi,

Building a client at ever request is very time consuming(+1 secs per request): 

1. get a token with credentials 
2. build client with token, 

thus poor user experience in app (JSF). Reusing a client per session is the option.  

BuiIding a Client with credentials does not retrieve a token, even after calling authorizationContext.isAuthed. That's why we always must build Client with token, which must again be obtained first with the annoying hack call to:
/oauth/authorize?client_id=openshift-challenging-client&response_type=token

We employ OpenShift v3.11.88

Am I misunderstanding the use cases of openshift-restclient-java?

Cheers,
Ridvan

**Comment by adietish** [comment] 2019-08-28 13:17
@ridvan70 Hi Ridvan, sorry for the lengthy delay. Your answer went buried in my daily mails. 

Yes, reusing the client instance per session is what we also do in Eclipse. And yes, authentication always uses a token, username & password are only means to get a token (as you can alternatively do via OAuth). I dont get though why you somehow loose the token? Or am I misunderstanding, missing something?

**Comment by ridvan70** [comment] 2019-08-28 16:17
Hi @adietish,

The issue is :
„BuiIding a Client with credentials does not retrieve a token“

Is this a feature or a bug?

Regards

**Comment by adietish** [comment] 2019-08-28 22:59
Hi @ridvan70 

not sure if we understand the same thing by "building a client". In our code we "build" a client instance and then trigger the authentication.
Looking into our code I am quite astonished that calling ```IAuthorizationContext#isAuthorized``` would not retrieve and store the token.
In our code we do the following (pseudocode, copy/pasted from https://github.com/jbosstools/jbosstools-openshift/blob/master/plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/connection/Connection.java#L237) 

``` 
IAuthorizationContext authContext = client.getAuthorizationContext();
authContext.setUserName(password);
authContext.setPassword(password);
authContext.isAuthorized();
```

Behind the scenes #isAuthorized would request the user resource, trigger authorization if it hits a 401 and store the token in the context once is done. You can see this here: https://github.com/openshift/openshift-restclient-java/blob/master/src/main/java/com/openshift/internal/restclient/okhttp/OpenShiftAuthenticator.java#L56
Maybe you can work with the source and insert a breakpoint there to see what happens if OpenShiftAuthenticator is called?
I'd also give it a shot if you have some snippet to share?

**Comment by adietish** [comment] 2019-08-29 14:48
@ridvan70 
I filed a PR to fix the leaking connections at #394

**Comment by adietish** [comment] 2019-10-16 14:24
Hi @ridvan70 

do you have further insights to share, please?

**Comment by ridvan70** [comment] 2019-10-16 21:56
No further insights then I've supplied above on Jun 24, for this topic.

For the topic „BuiIding a Client with credentials does not retrieve a token“ it's better to open another issue, I think.

**Comment by adietish** [comment] 2019-11-16 13:06
Hi @ridvan70 

quite a few changes to the client regarding authorization are on their way:
* #411 
* #413 
* #414 

I'd think that the bug you experience (that I unfortunately still can't reproduce when it comes to OpenShift 3.x) might hopefully be fixed. Once those are merged (openshift-restclient-java 8.1.1-SNAPSHOT), dare to test again?

**Comment by ridvan70** [comment] 2020-01-28 13:48
Hi,

let's close this topic. I will open a new one about Auth, if still exists in 8.1.1.

**Comment by adietish** [comment] 2020-04-15 15:35
@ridvan70 ok, thanks. Closing.

**Closed by adietish** 2020-04-15 15:35 UTC
